version: "3.3"

services:
  app:
    build: .
    volumes:
      - .:/var/www/app
      - ./docker/php-fpm.conf:/usr/local/etc/php-fpm.d/app.conf
      - ./docker/php.ini:/usr/local/etc/php/php.ini
      - php-socks:/var/run/php-fpm
    depends_on:
      - db
  nginx:
    image: nginx
    volumes:
      - .:/var/www/app
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx-app.conf:/etc/nginx/conf.d/default.conf
      - php-socks:/var/run/php-fpm
    depends_on:
      - app
    ports:
      - 8000:8000
  db:
    image: postgres:10
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata/app
    volumes:
      - db:/var/lib/postgresql/data/pgdata/app
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_LOGIN}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - 8010:80
volumes:
  php-socks:
  db:
