#!/usr/bin/env php
<?php
defined('PROJECT_DIR') or define('PROJECT_DIR', __DIR__);

require PROJECT_DIR . '/vendor/autoload.php';

if (getenv('APP_ENV') === 'dev') {
    Yiisoft\Composer\Config\Builder::rebuild();
}

require PROJECT_DIR . '/vendor/yiisoft/yii2/Yii.php';
require PROJECT_DIR . '/config/primary/bootstrap.php';

$application = (new yii\console\Application(require_once PROJECT_DIR . '/runtime/config/console.php'));
$exitCode = $application->run();
exit($exitCode);
